### PR TITLE
feat(vim-nav): add vim style navigation

### PR DESCRIPTION
**Pull request by nicksrandall**
I've added "vim" style navigation AND kept the search functionality by
requiring users to enter "search mode" be pressing the "/" key.

BREAKING CHANGE:
pressing a letter to jump to file name no longer works. To use that
functionality, you must use "search mode" by pressing "/" key.

### CODE REVIEW

**Comment by nicksrandall** [comment]
@aharris88 this PR should close #5, would you test it out and see if it works?

**Comment by agarrharr** [comment]
Wow, that was fast. This mostly works, but I'm seeing a few bugs.

For instance, when I type `/`, every time I type a key (even the delete key) after that, it repeats the prompt. 
screen shot 2016-03-02 at 8 04 47 am

Another issue is that if you type anything (other than j or k) it will show up next to "choose this directory". If you type delete, then "choose this directory" will disappear, and it will show everything you've typed including j and k. And then if you type j or k, "choose this directory will re-appear and the other letters disappear.
screen shot 2016-03-02 at 8 02 32 am
screen shot 2016-03-02 at 8 02 55 am

**Comment by nicksrandall** [comment]
@aharris88 I just pushed some fixes as well as add the ability to press "-" key to go up a directory (like vim). Will you test?

**Comment by agarrharr** [comment]
Almost there! :+1: 

The only bug I see now is that if you search and then delete everything that you typed, it repeats the prompt.

**Comment by nicksrandall** [comment]
@aharris88 fixed the delete issue. Anything else?

**Comment by agarrharr** [comment]
Awesome! Works great! :+1:

**Comment by nicksrandall** [comment]
@aharris88 Thx. I merged and created a new release. You'll need to make changes to the plop stuff so you/your team can use this.

**Pull request merged**
