### PR TITLE
Updated inquirer version

### PR DESCRIPTION
**Pull request by richardhomewood**
To fix 

https://github.com/nicksrandall/inquirer-directory/issues/8

### CODE REVIEW

**Comment by amwmedia** [comment]
@nicksrandall I'm working on an update to plop that includes updating to the latest version of inquirer. In order to do that without breaking compatibility with your plugin, this PR will need to get worked in.

**Comment by amwmedia** [comment]
If you're tests are using plop and that's why travis is failing this build, it might make sense for me to publish the new version of plop and then for you to publish the update. Let me know if you have any suggestions.

**Comment by amwmedia** [comment]
you can see the updated version of plop that uses inquirer 1.x and node-plop here https://github.com/amwmedia/plop/tree/feature/use-node-plop

**Comment by nicksrandall** [comment]
Fixed here: https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.1.0

**Pull request closed without merging**
